using Rutana.API.Fleet.Domain.Model.Commands;
using Rutana.API.Fleet.Domain.Model.ValueObjects;
using Rutana.API.Shared.Domain.Model.ValueObjects;

namespace Rutana.API.Fleet.Domain.Model.Aggregates;

/// <summary>
/// Vehicle Aggregate Root.
/// Represents a vehicle in the fleet management system.
/// </summary>
public class Vehicle
{
    /// <summary>
    /// Initializes a new instance of the <see cref="Vehicle"/> class.
    /// </summary>
    public Vehicle()
    {
        Plate = new LicensePlate();
        OrganizationId = new OrganizationId(0);
        Capacity = new VehicleCapacityKg();
        State = VehicleState.Enabled;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Vehicle"/> class with specified parameters.
    /// </summary>
    /// <param name="plate">The license plate.</param>
    /// <param name="organizationId">The organization identifier.</param>
    /// <param name="capacity">The vehicle capacity in kilograms.</param>
    private Vehicle(LicensePlate plate, OrganizationId organizationId, VehicleCapacityKg capacity)
    {
        Plate = plate;
        OrganizationId = organizationId;
        Capacity = capacity;
        State = VehicleState.Enabled;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Vehicle"/> class from a register vehicle command.
    /// </summary>
    /// <param name="command">The register vehicle command.</param>
    public Vehicle(RegisterVehicleCommand command) : this(
        LicensePlate.Create(command.Plate),
        new OrganizationId(command.OrganizationId),
        VehicleCapacityKg.Create(command.CapacityKg))
    {
    }

    /// <summary>
    /// Gets or sets the unique identifier of the vehicle (auto-generated by database).
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Gets the license plate of the vehicle.
    /// </summary>
    public LicensePlate Plate { get; private set; }

    /// <summary>
    /// Gets the organization identifier that owns this vehicle.
    /// </summary>
    public OrganizationId OrganizationId { get; private set; }

    /// <summary>
    /// Gets the capacity of the vehicle in kilograms.
    /// </summary>
    public VehicleCapacityKg Capacity { get; private set; }

    /// <summary>
    /// Gets the current state of the vehicle.
    /// </summary>
    public VehicleState State { get; private set; }

    /// <summary>
    /// Gets a value indicating whether the vehicle is enabled.
    /// </summary>
    public bool IsEnabled => State == VehicleState.Enabled;

    /// <summary>
    /// Gets a value indicating whether the vehicle is disabled.
    /// </summary>
    public bool IsDisabled => State == VehicleState.Disabled;

    /// <summary>
    /// Enables the vehicle, making it available for routes.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown when the vehicle is already enabled.</exception>
    public void Enable()
    {
        if (State == VehicleState.Enabled)
            throw new InvalidOperationException("Vehicle is already enabled.");

        State = VehicleState.Enabled;
    }

    /// <summary>
    /// Disables the vehicle, making it unavailable for routes.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown when the vehicle is already disabled.</exception>
    public void Disable()
    {
        if (State == VehicleState.Disabled)
            throw new InvalidOperationException("Vehicle is already disabled.");

        State = VehicleState.Disabled;
    }

    /// <summary>
    /// Updates the vehicle profile with new information.
    /// </summary>
    /// <param name="command">The update vehicle profile command.</param>
    public void UpdateProfile(UpdateVehicleProfileCommand command)
    {
        Plate = LicensePlate.Create(command.Plate);
        Capacity = VehicleCapacityKg.Create(command.CapacityKg);
    }

    /// <summary>
    /// Updates the vehicle state based on a command.
    /// </summary>
    /// <param name="command">The update vehicle state command.</param>
    /// <exception cref="ArgumentException">Thrown when an invalid state is provided.</exception>
    public void UpdateState(UpdateVehicleStateCommand command)
    {
        if (command.State.Equals("enabled", StringComparison.OrdinalIgnoreCase))
        {
            Enable();
        }
        else if (command.State.Equals("disabled", StringComparison.OrdinalIgnoreCase))
        {
            Disable();
        }
        else
        {
            throw new ArgumentException($"Invalid state: {command.State}. Valid states are 'enabled' or 'disabled'.");
        }
    }

    /// <summary>
    /// Factory method to create a new vehicle.
    /// </summary>
    /// <param name="command">The register vehicle command.</param>
    /// <returns>A new Vehicle instance.</returns>
    public static Vehicle Create(RegisterVehicleCommand command)
    {
        return new Vehicle(command);
    }
}