using Rutana.API.Shared.Domain.Repositories;
using Rutana.API.Suscriptions.Domain.Model.Aggregates;
using Rutana.API.Suscriptions.Domain.Model.Commands;
using Rutana.API.Suscriptions.Domain.Model.ValueObjects;
using Rutana.API.Suscriptions.Domain.Repositories;
using Rutana.API.Suscriptions.Domain.Services;

namespace Rutana.API.Suscriptions.Application.Internal.CommandServices;

/// <summary>
///     Application-level command service for the <see cref="Organization" /> aggregate.
/// </summary>
/// <param name="organizationRepository">
///     The <see cref="IOrganizationRepository" /> used to persist <see cref="Organization" /> instances.
/// </param>
/// <param name="unitOfWork">
///     The <see cref="IUnitOfWork" /> abstraction used to commit the changes as a single transaction.
/// </param>
public class OrganizationCommandService(IOrganizationRepository organizationRepository, IUnitOfWork unitOfWork)
    : IOrganizationCommandService
{
    /// <summary>
    ///     Handles the <see cref="CreateOrganizationCommand" /> by validating business rules,
    ///     creating a new <see cref="Organization" /> aggregate and committing the transaction
    ///     through the <see cref="IUnitOfWork" />.
    /// </summary>
    /// <param name="command">
    ///     The <see cref="CreateOrganizationCommand" /> containing the data required to create the organization.
    /// </param>
    public async Task Handle(CreateOrganizationCommand command)
    {
        // Check uniqueness by RUC at the domain/application level
        var ruc = new Ruc(command.Ruc);
        if (await organizationRepository.ExistsByRucAsync(ruc))
        {
            // In a more complete implementation, this could be a domain-specific exception type.
            throw new InvalidOperationException($"An organization with RUC '{command.Ruc}' already exists.");
        }

        var name = new OrganizationName(command.Name);

        // Id is generated by the database, so a default OrganizationId (0) is used here.
        var organization = Organization.Create(default, name, ruc);

        await organizationRepository.AddAsync(organization);
        await unitOfWork.CompleteAsync();
    }
}


