using Rutana.API.CRM.Domain.Model.Commands;
using Rutana.API.CRM.Domain.Model.ValueObjects;
using Rutana.API.Shared.Domain.Model.ValueObjects;

namespace Rutana.API.CRM.Domain.Model.Aggregates;

/// <summary>
/// Client Aggregate Root.
/// Represents a client in the CRM system.
/// </summary>
public class Client
{
    /// <summary>
    /// Initializes a new instance of the <see cref="Client"/> class.
    /// </summary>
    public Client()
    {
        CompanyName = new CompanyName();
        OrganizationId = new OrganizationId(0);
        IsEnabled = true;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Client"/> class with specified parameters.
    /// </summary>
    /// <param name="companyName">The company name.</param>
    /// <param name="organizationId">The organization identifier.</param>
    private Client(CompanyName companyName, OrganizationId organizationId)
    {
        CompanyName = companyName;
        OrganizationId = organizationId;
        IsEnabled = true;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Client"/> class from a register client command.
    /// </summary>
    /// <param name="command">The register client command.</param>
    public Client(RegisterClientCommand command) : this(
        CompanyName.Create(command.CompanyName),
        new OrganizationId(command.OrganizationId))
    {
    }

    /// <summary>
    /// Gets or sets the unique identifier of the client (auto-generated by database).
    /// </summary>
    public ClientId Id { get; internal set; } = new ClientId(0);

    /// <summary>
    /// Gets the company name of the client.
    /// </summary>
    public CompanyName CompanyName { get; private set; }

    /// <summary>
    /// Gets the organization identifier that owns this client.
    /// </summary>
    public OrganizationId OrganizationId { get; private set; }

    /// <summary>
    /// Gets a value indicating whether the client is enabled.
    /// </summary>
    public bool IsEnabled { get; private set; }

    /// <summary>
    /// Enables the client.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown when the client is already enabled.</exception>
    public void Enable()
    {
        if (IsEnabled)
            throw new InvalidOperationException("Client is already enabled.");

        IsEnabled = true;
    }

    /// <summary>
    /// Disables the client.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown when the client is already disabled.</exception>
    public void Disable()
    {
        if (!IsEnabled)
            throw new InvalidOperationException("Client is already disabled.");

        IsEnabled = false;
    }

    /// <summary>
    /// Updates the client state based on a command.
    /// </summary>
    /// <param name="command">The update client state command.</param>
    /// <exception cref="ArgumentException">Thrown when an invalid state is provided.</exception>
    public void UpdateState(UpdateClientStateCommand command)
    {
        if (command.State.Equals("enabled", StringComparison.OrdinalIgnoreCase))
        {
            Enable();
        }
        else if (command.State.Equals("disabled", StringComparison.OrdinalIgnoreCase))
        {
            Disable();
        }
        else
        {
            throw new ArgumentException($"Invalid state: {command.State}. Valid states are 'enabled' or 'disabled'.");
        }
    }

    /// <summary>
    /// Factory method to create a new client.
    /// </summary>
    /// <param name="command">The register client command.</param>
    /// <returns>A new Client instance.</returns>
    public static Client Create(RegisterClientCommand command)
    {
        return new Client(command);
    }
}