using Rutana.API.CRM.Domain.Model.Commands;
using Rutana.API.CRM.Domain.Model.ValueObjects;

namespace Rutana.API.CRM.Domain.Model.Aggregates;

/// <summary>
/// Location Aggregate Root.
/// Represents a client location (delivery/pickup point) in the CRM system.
/// </summary>
public class Location
{
    /// <summary>
    /// Initializes a new instance of the <see cref="Location"/> class.
    /// </summary>
    public Location()
    {
        Name = new LocationName();
        ClientId = new ClientId();
        Proximity = Proximity.Medium;
        IsEnabled = true;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Location"/> class with specified parameters.
    /// </summary>
    /// <param name="name">The location name.</param>
    /// <param name="clientId">The client identifier.</param>
    /// <param name="proximity">The proximity level.</param>
    private Location(LocationName name, ClientId clientId, Proximity proximity)
    {
        Name = name;
        ClientId = clientId;
        Proximity = proximity;
        IsEnabled = true;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Location"/> class from a register location command.
    /// </summary>
    /// <param name="command">The register location command.</param>
    public Location(RegisterLocationCommand command) : this(
        LocationName.Create(command.Name),
        new ClientId(command.ClientId),
        command.Proximity)
    {
    }

    /// <summary>
    /// Gets or sets the unique identifier of the location (auto-generated by database).
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Gets the name of the location.
    /// </summary>
    public LocationName Name { get; private set; }

    /// <summary>
    /// Gets the client identifier that owns this location.
    /// </summary>
    public ClientId ClientId { get; private set; }

    /// <summary>
    /// Gets the proximity level of the location.
    /// </summary>
    public Proximity Proximity { get; private set; }

    /// <summary>
    /// Gets a value indicating whether the location is enabled.
    /// </summary>
    public bool IsEnabled { get; private set; }

    /// <summary>
    /// Enables the location.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown when the location is already enabled.</exception>
    public void Enable()
    {
        if (IsEnabled)
            throw new InvalidOperationException("Location is already enabled.");

        IsEnabled = true;
    }

    /// <summary>
    /// Disables the location.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown when the location is already disabled.</exception>
    public void Disable()
    {
        if (!IsEnabled)
            throw new InvalidOperationException("Location is already disabled.");

        IsEnabled = false;
    }

    /// <summary>
    /// Factory method to create a new location.
    /// </summary>
    /// <param name="command">The register location command.</param>
    /// <returns>A new Location instance.</returns>
    public static Location Create(RegisterLocationCommand command)
    {
        return new Location(command);
    }
}