using Rutana.API.CRM.Domain.Model.Commands;
using Rutana.API.CRM.Domain.Model.ValueObjects;

namespace Rutana.API.CRM.Domain.Model.Aggregates;

/// <summary>
/// Location Aggregate Root.
/// Represents a physical location associated with a client.
/// </summary>
public class Location
{
    /// <summary>
    /// Initializes a new instance of the <see cref="Location"/> class.
    /// </summary>
    public Location()
    {
        Name = new LocationName();
        Proximity = Proximity.Near;
        ClientId = new ClientId(0);
        IsEnabled = true;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Location"/> class with specified parameters.
    /// </summary>
    /// <param name="name">The location name.</param>
    /// <param name="proximity">The proximity information.</param>
    /// <param name="clientId">The client identifier.</param>
    private Location(LocationName name, Proximity proximity, ClientId clientId)
    {
        Name = name;
        Proximity = proximity;
        ClientId = clientId;
        IsEnabled = true;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Location"/> class from a register location command.
    /// </summary>
    /// <param name="command">The register location command.</param>
    public Location(RegisterLocationCommand command) : this(
        LocationName.Create(command.Name),
        command.Proximity,
        new ClientId(command.ClientId))
    {
    }

    /// <summary>
    /// Gets or sets the unique identifier of the location (auto-generated by database).
    /// </summary>
    public LocationId Id { get; internal set; } = new LocationId(0);

    /// <summary>
    /// Gets the location name.
    /// </summary>
    public LocationName Name { get; private set; }

    /// <summary>
    /// Gets the proximity information (coordinates and address).
    /// </summary>
    public Proximity Proximity { get; private set; }

    /// <summary>
    /// Gets the client identifier that owns this location.
    /// </summary>
    public ClientId ClientId { get; private set; }

    /// <summary>
    /// Gets a value indicating whether the location is enabled.
    /// </summary>
    public bool IsEnabled { get; private set; }

    /// <summary>
    /// Enables the location.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown when the location is already enabled.</exception>
    public void Enable()
    {
        if (IsEnabled)
            throw new InvalidOperationException("Location is already enabled.");

        IsEnabled = true;
    }

    /// <summary>
    /// Disables the location.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown when the location is already disabled.</exception>
    public void Disable()
    {
        if (!IsEnabled)
            throw new InvalidOperationException("Location is already disabled.");

        IsEnabled = false;
    }

    /// <summary>
    /// Updates the location state based on a command.
    /// </summary>
    /// <param name="command">The update location state command.</param>
    /// <exception cref="ArgumentException">Thrown when an invalid state is provided.</exception>
    public void UpdateState(UpdateLocationStateCommand command)
    {
        if (command.State.Equals("enabled", StringComparison.OrdinalIgnoreCase))
        {
            Enable();
        }
        else if (command.State.Equals("disabled", StringComparison.OrdinalIgnoreCase))
        {
            Disable();
        }
        else
        {
            throw new ArgumentException($"Invalid state: {command.State}. Valid states are 'enabled' or 'disabled'.");
        }
    }

    /// <summary>
    /// Factory method to create a new location.
    /// </summary>
    /// <param name="command">The register location command.</param>
    /// <returns>A new Location instance.</returns>
    public static Location Create(RegisterLocationCommand command)
    {
        return new Location(command);
    }
}