// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rutana.API.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace Rutana.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251125193707_InitialCreate_IAM")]
    partial class InitialCreate_IAM
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Rutana.API.CRM.Domain.Model.Aggregates.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("p_k_clients");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("i_x_clients_organization_id");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("Rutana.API.CRM.Domain.Model.Aggregates.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Proximity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("proximity");

                    b.HasKey("Id")
                        .HasName("p_k_locations");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("i_x_locations_client_id");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("Rutana.API.Fleet.Domain.Model.Aggregates.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("p_k_vehicles");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("i_x_vehicles_organization_id");

                    b.ToTable("vehicles");
                });

            modelBuilder.Entity("Rutana.API.Suscriptions.Domain.Model.Aggregates.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_organizations");

                    b.ToTable("organizations");
                });

            modelBuilder.Entity("Rutana.API.CRM.Domain.Model.Aggregates.Client", b =>
                {
                    b.HasOne("Rutana.API.Suscriptions.Domain.Model.Aggregates.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_clients__organization_organization_id");

                    b.OwnsOne("Rutana.API.CRM.Domain.Model.ValueObjects.CompanyName", "CompanyName", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("company_name");

                            b1.HasKey("Id")
                                .HasName("p_k_clients");

                            b1.ToTable("clients");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_clients_clients_id");
                        });

                    b.Navigation("CompanyName")
                        .IsRequired();
                });

            modelBuilder.Entity("Rutana.API.CRM.Domain.Model.Aggregates.Location", b =>
                {
                    b.HasOne("Rutana.API.CRM.Domain.Model.Aggregates.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_locations_clients_client_id");

                    b.OwnsOne("Rutana.API.CRM.Domain.Model.ValueObjects.LocationName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("name");

                            b1.HasKey("Id")
                                .HasName("p_k_locations");

                            b1.ToTable("locations");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_locations_locations_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Rutana.API.Fleet.Domain.Model.Aggregates.Vehicle", b =>
                {
                    b.HasOne("Rutana.API.Suscriptions.Domain.Model.Aggregates.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_vehicles__organization_organization_id");

                    b.OwnsOne("Rutana.API.Fleet.Domain.Model.ValueObjects.LicensePlate", "Plate", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("plate");

                            b1.HasKey("Id")
                                .HasName("p_k_vehicles");

                            b1.ToTable("vehicles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_vehicles_vehicles_id");
                        });

                    b.OwnsOne("Rutana.API.Fleet.Domain.Model.ValueObjects.VehicleCapacityKg", "Capacity", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("capacity_kg");

                            b1.HasKey("Id")
                                .HasName("p_k_vehicles");

                            b1.ToTable("vehicles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_vehicles_vehicles_id");
                        });

                    b.Navigation("Capacity")
                        .IsRequired();

                    b.Navigation("Plate")
                        .IsRequired();
                });

            modelBuilder.Entity("Rutana.API.Suscriptions.Domain.Model.Aggregates.Organization", b =>
                {
                    b.OwnsOne("Rutana.API.Suscriptions.Domain.Model.ValueObjects.OrganizationName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("name");

                            b1.HasKey("Id")
                                .HasName("p_k_organizations");

                            b1.ToTable("organizations");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_organizations_organizations_id");
                        });

                    b.OwnsOne("Rutana.API.Suscriptions.Domain.Model.ValueObjects.Ruc", "Ruc", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("ruc");

                            b1.HasKey("Id")
                                .HasName("p_k_organizations");

                            b1.ToTable("organizations");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_organizations_organizations_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Ruc")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
