using Rutana.API.CRM.Domain.Model.ValueObjects;
using Rutana.API.Fleet.Domain.Model.ValueObjects;
using Rutana.API.Planning.Domain.Model.Entities;
using Rutana.API.Planning.Domain.Model.ValueObjects;
using Rutana.API.Shared.Domain.Model.ValueObjects;

namespace Rutana.API.Planning.Domain.Model.Aggregates;

/// <summary>
/// Route Aggregate Root.
/// Represents a published and active route.
/// </summary>
public class Route
{
    private readonly List<Delivery> _deliveries = new();
    private readonly List<RouteTeamMember> _teamMembers = new();

    /// <summary>
    /// Default constructor for EF Core.
    /// </summary>
    public Route()
    {
        OrganizationId = new OrganizationId(0);
        ColorCode = new ColorCode();
        VehicleId = new VehicleId(0);
        StartedAt = DateTime.UtcNow;
        EndedAt = null;
        Status = RouteStatus.Published;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Route"/> class.
    /// </summary>
    /// <param name="organizationId">The organization identifier.</param>
    /// <param name="colorCode">The color code.</param>
    /// <param name="vehicleId">The vehicle identifier.</param>
    /// <param name="startedAt">The start time.</param>
    /// <param name="endedAt">The end time.</param>
    /// <param name="deliveries">The list of deliveries.</param>
    /// <param name="teamMembers">The list of team members.</param>
    private Route(
        OrganizationId organizationId,
        ColorCode colorCode,
        VehicleId vehicleId,
        DateTime startedAt,
        DateTime? endedAt,
        List<Delivery> deliveries,
        List<RouteTeamMember> teamMembers)
    {
        OrganizationId = organizationId;
        ColorCode = colorCode;
        VehicleId = vehicleId;
        StartedAt = startedAt;
        EndedAt = endedAt;
        Status = RouteStatus.Published;
        
        _deliveries.AddRange(deliveries);
        _teamMembers.AddRange(teamMembers);
    }

    /// <summary>
    /// Gets or sets the unique identifier of the route (auto-generated by database).
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Gets the organization identifier that owns this route.
    /// </summary>
    public OrganizationId OrganizationId { get; private set; }

    /// <summary>
    /// Gets the color code for route identification.
    /// </summary>
    public ColorCode ColorCode { get; private set; }

    /// <summary>
    /// Gets the vehicle identifier assigned to this route.
    /// </summary>
    /// <remarks>
    /// References Fleet bounded context (Vehicle aggregate).
    /// </remarks>
    public VehicleId VehicleId { get; private set; }

    /// <summary>
    /// Gets the actual start time of the route.
    /// </summary>
    public DateTime StartedAt { get; private set; }

    /// <summary>
    /// Gets the actual end time of the route.
    /// </summary>
    public DateTime? EndedAt { get; private set; }

    /// <summary>
    /// Gets the current status of the route.
    /// </summary>
    public RouteStatus Status { get; private set; }

    /// <summary>
    /// Gets the list of deliveries for this route.
    /// </summary>
    public IReadOnlyCollection<Delivery> Deliveries => _deliveries.AsReadOnly();

    /// <summary>
    /// Gets the list of team members assigned to this route.
    /// </summary>
    public IReadOnlyCollection<RouteTeamMember> TeamMembers => _teamMembers.AsReadOnly();

    /// <summary>
    /// Starts the route execution.
    /// </summary>
    public void Start()
    {
        if (Status != RouteStatus.Published)
        {
            throw new InvalidOperationException("Only published routes can be started.");
        }

        StartedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Completes the route execution.
    /// </summary>
    public void Complete()
    {
        if (Status != RouteStatus.Published)
        {
            throw new InvalidOperationException("Only published routes can be completed.");
        }

        // Verify all deliveries are completed or rejected
        if (_deliveries.Any(d => d.Status == DeliveryStatus.Pending || d.Status == DeliveryStatus.InProgress))
        {
            throw new InvalidOperationException("Cannot complete route with pending or in-progress deliveries.");
        }

        Status = RouteStatus.Completed;
        EndedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Creates a Route from a RouteDraft.
    /// </summary>
    /// <param name="draft">The route draft.</param>
    /// <returns>A new Route instance.</returns>
    /// <exception cref="InvalidOperationException">Thrown when draft is not valid for publishing.</exception>
    public static Route FromDraft(RouteDraft draft)
    {
        draft.ValidateForPublishing();

        // Create copies of deliveries and team members
        var deliveries = draft.Deliveries
            .Select(d => new Delivery(d.LocationId))
            .ToList();

        var teamMembers = draft.TeamMembers
            .Select(tm => new RouteTeamMember(tm.UserId))
            .ToList();

        return new Route(
            draft.OrganizationId,
            draft.ColorCode,
            draft.VehicleId,
            draft.StartedAt!.Value,
            draft.EndedAt,
            deliveries,
            teamMembers);
    }
}