using Rutana.API.CRM.Domain.Model.ValueObjects;
using Rutana.API.Fleet.Domain.Model.ValueObjects;
using Rutana.API.IAM.Domain.Model.ValueObject;
using Rutana.API.Planning.Domain.Model.Commands;
using Rutana.API.Planning.Domain.Model.Entities;
using Rutana.API.Planning.Domain.Model.ValueObjects;
using Rutana.API.Shared.Domain.Model.ValueObjects;

namespace Rutana.API.Planning.Domain.Model.Aggregates;

/// <summary>
/// RouteDraft Aggregate Root.
/// Represents an editable draft of a route before publication.
/// </summary>
public class RouteDraft
{
    private readonly List<Delivery> _deliveries = new();
    private readonly List<RouteTeamMember> _teamMembers = new();

    /// <summary>
    /// Default constructor for EF Core.
    /// </summary>
    public RouteDraft()
    {
        OrganizationId = new OrganizationId(0);
        ColorCode = new ColorCode();
        VehicleId = null;
        ExecutionDate = DateTime.UtcNow.Date;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="RouteDraft"/> class.
    /// </summary>
    /// <param name="organizationId">The organization identifier.</param>
    /// <param name="colorCode">The color code for route identification.</param>
    /// <param name="executionDate">The date when the route will be executed.</param>
    private RouteDraft(OrganizationId organizationId, ColorCode colorCode, DateTime executionDate)
    {
        OrganizationId = organizationId;
        ColorCode = colorCode;
        VehicleId = null;
        ExecutionDate = executionDate.Date; // Store only the date part
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="RouteDraft"/> class from a create command.
    /// </summary>
    /// <param name="command">The create route draft command.</param>
    public RouteDraft(CreateRouteDraftCommand command) : this(
        new OrganizationId(command.OrganizationId),
        ColorCode.Create(command.ColorCode),
        command.ExecutionDate)
    {
    }

    /// <summary>
    /// Gets or sets the unique identifier of the route draft (auto-generated by database).
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Gets the organization identifier that owns this route draft.
    /// </summary>
    public OrganizationId OrganizationId { get; private set; }

    /// <summary>
    /// Gets the color code for route identification.
    /// </summary>
    public ColorCode ColorCode { get; private set; }

    /// <summary>
    /// Gets the vehicle identifier assigned to this route.
    /// </summary>
    /// <remarks>
    /// References Fleet bounded context (Vehicle aggregate).
    /// </remarks>
    public VehicleId? VehicleId { get; private set; }

    /// <summary>
    /// Gets the date when the route will be executed.
    /// </summary>
    /// <remarks>
    /// This date is used for planning and filtering routes by execution date.
    /// Only the date part is stored (time is ignored).
    /// StartedAt and EndedAt are only available in Route (published route), not in RouteDraft.
    /// </remarks>
    public DateTime ExecutionDate { get; private set; }

    /// <summary>
    /// Gets the list of deliveries for this route.
    /// </summary>
    public IReadOnlyCollection<Delivery> Deliveries => _deliveries.AsReadOnly();

    /// <summary>
    /// Gets the list of team members assigned to this route.
    /// </summary>
    public IReadOnlyCollection<RouteTeamMember> TeamMembers => _teamMembers.AsReadOnly();

    /// <summary>
    /// Applies changes to the route draft.
    /// </summary>
    /// <param name="command">The save route draft changes command.</param>
    public void ApplyChanges(SaveRouteDraftChangesCommand command)
    {
        // Update color code if provided
        if (!string.IsNullOrWhiteSpace(command.ColorCode))
        {
            ColorCode = ColorCode.Create(command.ColorCode);
        }

        // Update vehicle if provided
        if (command.VehicleId.HasValue)
        {
            VehicleId = new VehicleId(command.VehicleId.Value);
        }

        // Update execution date if provided
        if (command.ExecutionDate.HasValue)
        {
            ExecutionDate = command.ExecutionDate.Value.Date; // Store only the date part
        }

        // Update deliveries (clear and add new ones)
        _deliveries.Clear();
        if (command.LocationIds != null && command.LocationIds.Any())
        {
            foreach (var locationId in command.LocationIds)
            {
                _deliveries.Add(new Delivery(new LocationId(locationId), ExecutionDate));
            }
        }

        // Update team members (clear and add new ones)
        _teamMembers.Clear();
        if (command.TeamMemberIds != null && command.TeamMemberIds.Any())
        {
            foreach (var userId in command.TeamMemberIds)
            {
                _teamMembers.Add(new RouteTeamMember(new UserId(userId)));
            }
        }
    }

    /// <summary>
    /// Adds a location to the route.
    /// </summary>
    /// <param name="locationId">The location identifier to add.</param>
    public void AddLocation(LocationId locationId)
    {
        if (_deliveries.Any(d => d.LocationId.Value == locationId.Value))
        {
            throw new InvalidOperationException("Location is already added to this route.");
        }

        _deliveries.Add(new Delivery(locationId, ExecutionDate));
    }

    /// <summary>
    /// Assigns a team member to the route.
    /// </summary>
    /// <param name="userId">The user identifier to assign.</param>
    public void AssignMember(UserId userId)
    {
        if (_teamMembers.Any(tm => tm.UserId.Id == userId.Id))
        {
            throw new InvalidOperationException("User is already assigned to this route.");
        }

        _teamMembers.Add(new RouteTeamMember(userId));
    }

    /// <summary>
    /// Assigns a vehicle to the route.
    /// </summary>
    /// <param name="vehicleId">The vehicle identifier to assign.</param>
    public void AssignVehicle(VehicleId vehicleId)
    {
        VehicleId = vehicleId;
    }

    /// <summary>
    /// Validates if the route draft can be published.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown when validation fails.</exception>
    public void ValidateForPublishing()
    {
        if (VehicleId == null)
        {
            throw new InvalidOperationException("Cannot publish route without assigned vehicle.");
        }

        if (!_deliveries.Any())
        {
            throw new InvalidOperationException("Cannot publish route without deliveries.");
        }
    }

    /// <summary>
    /// Factory method to create a new route draft.
    /// </summary>
    /// <param name="command">The create route draft command.</param>
    /// <returns>A new RouteDraft instance.</returns>
    public static RouteDraft Create(CreateRouteDraftCommand command)
    {
        return new RouteDraft(command);
    }
}